### ISSUE TITLE
[naming] Rename `space` to `billboard`

### ISSUE THREAD

**Issue by limbofeather** [zestymarket/billboard#124]
In order to make the terminology more clear to newcomers to Zesty, I'd like to suggest a rename of any mentions of the word "space" to "billboard". It's less ambiguous and would make it consistent with the UI.

**Comment by JSeam2** [comment]
There may be intentions to generalize the sdk to support more than just 2D meshes suppose we do support 3D assets. To redecide on the the name change.

**Comment by limbofeather** [comment]
Closing since we don't want to continue with the rename.
